apiVersion: 1

datasources:
  - name: CTIC Postgres
    uid: CTICPG
    type: postgres
    access: proxy
    url: postgres:5432
    user: $PGUSER
    database: $PGDATABASE
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $PGPASSWORD
    isDefault: true
